services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    environment:
      TZ: ${TZ}
      RAILS_ENV: ${RAILS_ENV}
    links:
      - db
    ports:
      - "${EXPOSE_APP_PORT}:3000"
    depends_on:
      - db

volumes:
  db-mysql-data:
